language: cpp
dist: xenial
sudo: required
branches:
 only:
   - master

# Use matrix expansion for linux/osx
os:
  - linux
  - osx
 
compiler:
  - gcc
  - clang

install:
  # Linux
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get -qq install libsdl2-dev -y;
      sdl2-config --version;
      sudo apt-get -qq install libsdl2-image-dev -y;
      sudo apt-get -qq install libsdl2-ttf-dev -y;
      sudo apt-get -qq install libxml2-dev -y;
 
      git clone https://github.com/baylej/tmx;
      cd tmx;
      mkdir build && cd build;
      cmake ..;
      make;
      sudo make install;
      cd ../..;
    fi
  
  # Mac OS X  
  # n.b. libxml2 2.9.7 is already installed
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
      brew update;
      brew install sdl2;
      brew install sdl2_image;
      brew install sdl2_ttf;
      brew install zlib;

      git clone https://github.com/baylej/tmx;
      cd tmx;
      mkdir build && cd build;
      cmake ..;
      make;
      sudo make install;
      cd ../..;
      
      chmod +x tools/bin/macosx/genie;
    fi 
    
  # Windows
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
      scripts/install_sdl.bat;
      ./install_tmx_travis.bat;
    fi
    
script:
  - ./genie_gmake.sh
  - cd build
  - make config=debug
  - make config=dev
  - make config=release

# Explicitly include Windows job
matrix:
  include:
    - name: "Windows MSVC"
      os: windows
      env:
        - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - scripts/genie_vs2017.bat;
          cd build
        # n.b. have to use double slash to use Windows style / command line option in Git Bash
        - MSBuild.exe //p:Platform=Win32 //p:Configuration=Debug sdl2-sokoban.sln 
        - MSBuild.exe //p:Platform=Win32 //p:Configuration=Dev sdl2-sokoban.sln
        - MSBuild.exe //p:Platform=Win32 //p:Configuration=Release sdl2-sokoban.sln 
        - MSBuild.exe //p:Platform=x64 //p:Configuration=Debug sdl2-sokoban.sln 
        - MSBuild.exe //p:Platform=x64 //p:Configuration=Dev sdl2-sokoban.sln
        - MSBuild.exe //p:Platform=x64 //p:Configuration=Release sdl2-sokoban.sln         

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
    
  